spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    serialization: {write-dates-as-timestamps: true}
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jiajing
    password: jiajing
    url: jdbc:mysql://218.91.114.137:3306/jiajing?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  # REDIS (RedisProperties)
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: 218.91.114.137
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tRdpPJb5vpvJsPHUvzd
      keysecret: 9zJeQDwkgg9KaNotYCHvn721cEOnXJ
      bucketname: mingzhe-file

# 文件地址
file:
  #文件保存路径 只是个demo
  url: D:\\project\\spring-boot-scaffold\\src\\main\\resources\\upload\\

#解决缓存目录被系统清除的问题 稳定版暂未配置
server:
  tomcat:
    basedir: ./tmp
##自定义配置
taskmagprops:
  expireTime: 18000000
  checkLoginUrl: /download.*,/swagger.*,/vueAdmin-template.*,/static.*,/a2billing.*,/favicon.*,/webjars/springfox-swagger-ui.*,/v2/api-docs.*,/user/add,/user/login,/user/logout,/file/uploadSingle,/file.*,/course/detail,/course/findByModal,/article/detail,/article/findByModal,/article/type/detail,/article/type/findByModal,/test/question/detail,/test/question/findByModal,/paper/detail,/paper/findByModal,/answer/add,/moment/like/addOrCancel,/cover/detail,/cover/findByModal,/user/detail,/user/findByModal,/user/findAllColumns,/sys/role/findByModal,/user/detailByToken
  filedir: api-mag/
  fileBasePath: upload/

logging:
  level:
    com:
      company:
        project:
          dao: DEBUG
